### ISSUE TITLE
Error handling when stacking or calling finalize

### ISSUE THREAD

**Issue by igrigorik** [WICG/video-editing#1]
I like the fact that you can stack desired edits and batch the final operation, which would in turn allow the user agent to run optimizations against said graph, etc. However, this also means delayed (error) feedback to the developer stacking these operations. Trivial example here is: given a 1m video, trim 10:20s > trim 15:20s — instead of trimming against new 0-10 clip the developer erroneously tried to trim the last 5 seconds of first clip. 

Is there anything we can do here to improve developer ergonomics?

1. Could we run error checks when new operation is added to the queue?
2. Could we surface errors or list of discarded operations when finalize is called?
3. ... some other strategy?

/cc @gregwhitworth

**Comment by ykh015** [comment]
Hi @igrigorik. I apologize for this delayed response. 
I have tried addressing your feedback [here](https://github.com/WICG/video-editing/commit/ba70a81aa89bac76d5849d5fe66d02d58fe1fd97). Thanks !

**Comment by igrigorik** [comment]
Thank Yash! Quick first pass, looks great. From here, let's see what feedback we get from folks putting this into practice.
